version: "3.9"

services:
  db_tareas:
    container_name: db_tareas
    restart: always
    image: postgres:15.8
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=admin_tareas
      - POSTGRES_DB=tareas
